# frozen_string_literal: true

require "bundler/gem_tasks"
require "minitest/test_task"

Minitest::TestTask.create do |t|
  t.warning = false
  t.test_globs = (
    Rake::FileList["test/**/test_*.rb", "test/**/*_test.rb"]
    .exclude("test/fixtures/**/*")
  )
end

task default: :test
